/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSellRouteImport } from './routes/_app/sell'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppBuyRouteImport } from './routes/_app/buy'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyRoute = AppBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buy': typeof AppBuyRoute
  '/contact': typeof AppContactRoute
  '/feedback': typeof AppFeedbackRoute
  '/home': typeof AppHomeRoute
  '/sell': typeof AppSellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buy': typeof AppBuyRoute
  '/contact': typeof AppContactRoute
  '/feedback': typeof AppFeedbackRoute
  '/home': typeof AppHomeRoute
  '/sell': typeof AppSellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/buy': typeof AppBuyRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/sell': typeof AppSellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/buy'
    | '/contact'
    | '/feedback'
    | '/home'
    | '/sell'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/buy' | '/contact' | '/feedback' | '/home' | '/sell'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/buy'
    | '/_app/contact'
    | '/_app/feedback'
    | '/_app/home'
    | '/_app/sell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sell': {
      id: '/_app/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buy': {
      id: '/_app/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof AppBuyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuyRoute: typeof AppBuyRoute
  AppContactRoute: typeof AppContactRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppHomeRoute: typeof AppHomeRoute
  AppSellRoute: typeof AppSellRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuyRoute: AppBuyRoute,
  AppContactRoute: AppContactRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppHomeRoute: AppHomeRoute,
  AppSellRoute: AppSellRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
